version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
     - ./rails_sample:/root
    ports:
      - "3000:3000"
    depends_on:
      - db
